/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { jurisdictions } from "../../lib/evidence";
import { schemes } from "../../lib/schemes";
import SchemesClient from "./schemes-client";

export const metadata:Metadata={title:"Loans & schemes navigator — India Evidence Dashboard",description:"Privacy-safe, source-linked guidance for Indian government-supported loans, credit support and application routes."};

export default function SchemesPage(){return <main className="scheme-shell">
  <header className="record-header"><a className="record-brand" href="/"><span className="brand-mark"/><b>India Evidence <em>Dashboard</em></b></a><nav><a href="#finder">Find support</a><a href="#catalogue">Catalogue</a><a href="#access">How to apply</a><a href="#state-gap">State coverage</a></nav><a className="record-compare" href="/explore">All evidence</a></header>
  <section className="scheme-hero"><p className="eyebrow">Loans, subsidies & credit support</p><h1>Find the doorway.<br/><span>Know the conditions.</span></h1><p>Choose a state and a practical need. The navigator shows possible official routes—not guaranteed eligibility, approval, interest rate or disbursement.</p><div className="scheme-privacy"><b>No Aadhaar. No bank details. No profile saved.</b><span>This release performs simple matching in your browser and sends applications only to public official doorways.</span></div></section>
  <SchemesClient schemes={schemes} jurisdictions={jurisdictions.map(item=>item.name)}/>
  <section className="scheme-access" id="access"><div><p className="eyebrow">Before applying</p><h2>A government label does not remove the lender’s decision.</h2></div><ol><li><b>01</b><strong>Confirm the source</strong><p>Check the responsible ministry, current guidelines and application domain. Ignore sponsored look-alike pages.</p></li><li><b>02</b><strong>Prepare the activity</strong><p>Loan applications require a real purpose, cost estimate, repayment case and supporting documents—not only identity proof.</p></li><li><b>03</b><strong>Read all costs</strong><p>Ask for the interest rate, fees, insurance, guarantee fee, moratorium, EMI and security conditions in writing.</p></li><li><b>04</b><strong>Track and escalate</strong><p>Save the application number. Use the official portal, lender grievance process and RBI complaint route where applicable.</p></li></ol></section>
  <section className="scheme-state-gap" id="state-gap"><div><p className="eyebrow">36-jurisdiction coverage rule</p><h2>National access now. State catalogues next.</h2><p>All current states and union territories are selectable. The verified records in this release are national programmes available through state-level banks, missions or implementing agencies. Individual state-government loan corporations and department schemes are not yet claimed as complete.</p></div><div><strong>State catalogue source</strong><p>Use myScheme’s official State/UT filtering while this dashboard’s state records are reviewed one by one.</p><a href="https://www.myscheme.gov.in/" target="_blank" rel="noreferrer">Open official myScheme finder ↗</a><small>Discovery does not prove sanction, continuing budget availability or current local implementation.</small></div></section>
  <footer className="record-footer"><a href="/">← National dashboard</a><a href="/explore">All states and UTs</a><a href="/#methodology">Methodology</a></footer>
  </main>}
