"use client";

import { useMemo, useState } from "react";
import { schemeNeeds, schemeProfiles, type SchemeRecord } from "../../lib/schemes";

export default function SchemesClient({schemes,jurisdictions}:{schemes:SchemeRecord[];jurisdictions:string[]}){
  const [state,setState]=useState("Maharashtra");
  const [profile,setProfile]=useState("All profiles");
  const [need,setNeed]=useState("All needs");
  const [area,setArea]=useState("All areas");
  const [query,setQuery]=useState("");
  const [category,setCategory]=useState("All support types");

  const possibleMatches=useMemo(()=>schemes.filter(scheme=>(profile === "All profiles" || scheme.audience.includes(profile))&&(need === "All needs" || scheme.needs.includes(need))&&(area === "All areas" || scheme.area.includes(area as "Rural"|"Urban"))),[schemes,profile,need,area]);
  const shown=useMemo(()=>possibleMatches.filter(scheme=>(category === "All support types" || scheme.supportType === category)&&(!query || JSON.stringify(scheme).toLowerCase().includes(query.toLowerCase()))),[possibleMatches,category,query]);
  const active=shown.filter(item=>item.status !== "Legacy / successor pending").length;

  return <>
    <section className="scheme-finder" id="finder"><div className="scheme-finder-head"><div><p className="eyebrow">Private, non-binding match</p><h2>What are you trying to access?</h2></div><p>Only broad attributes are used. Nothing is transmitted or retained. Final eligibility always comes from the official scheme and lender.</p></div><div className="scheme-question-grid"><label>State or union territory<select value={state} onChange={event=>setState(event.target.value)}>{jurisdictions.map(item=><option key={item}>{item}</option>)}</select></label><label>Applicant profile<select value={profile} onChange={event=>setProfile(event.target.value)}>{schemeProfiles.map(item=><option key={item}>{item}</option>)}</select></label><label>Primary need<select value={need} onChange={event=>setNeed(event.target.value)}>{schemeNeeds.map(item=><option key={item}>{item}</option>)}</select></label><label>Area<select value={area} onChange={event=>setArea(event.target.value)}><option>All areas</option><option>Rural</option><option>Urban</option></select></label></div><div className="scheme-match-result"><span>Possible routes for <b>{state}</b></span><strong>{active}</strong><p>open or lender-mediated records shown after matching. This is not an eligibility decision.</p><a href="https://www.myscheme.gov.in/find-scheme/screen-2" target="_blank" rel="noreferrer">Check official state-scheme finder ↗</a></div></section>

    <section className="scheme-catalogue" id="catalogue"><div className="scheme-catalogue-head"><div><p className="eyebrow">Verified seed catalogue</p><h2>Compare the route—not just the maximum amount.</h2></div><p>{state} currently inherits these verified national records. State-only programme ingestion remains visibly incomplete.</p></div><div className="scheme-controls"><label>Search<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="MUDRA, student, collateral…"/></label><label>Support type<select value={category} onChange={event=>setCategory(event.target.value)}><option>All support types</option>{Array.from(new Set(schemes.map(item=>item.supportType))).sort().map(item=><option key={item}>{item}</option>)}</select></label><button onClick={()=>{setQuery("");setCategory("All support types");setProfile("All profiles");setNeed("All needs");setArea("All areas")}}>Clear filters</button><a href="/api/schemes/export">Download verified seed CSV ↓</a></div><div className="scheme-count"><b>{shown.length}</b> of {schemes.length} source-reviewed records <span>National programmes · state-specific gaps disclosed</span></div>
      <div className="scheme-grid">{shown.map(scheme=><article key={scheme.id} className="scheme-card"><div className="scheme-card-head"><span>{scheme.category} · {scheme.supportType}</span><b data-status={scheme.status}>{scheme.status}</b><h3>{scheme.shortName}</h3><p>{scheme.name}</p></div><div className="scheme-amount"><span>Published support structure</span><strong>{scheme.amount}</strong></div><dl><div><dt>Likely users</dt><dd>{scheme.audience.join(" · ")}</dd></div><div><dt>Interest</dt><dd>{scheme.interest}</dd></div><div><dt>Collateral / guarantee</dt><dd>{scheme.collateral}</dd></div><div><dt>Application route</dt><dd>{scheme.applicationRoute}</dd></div></dl><details><summary>Eligibility, documents & steps <span>+</span></summary><div className="scheme-detail-columns"><section><h4>Published conditions</h4><ul>{scheme.eligibility.map(item=><li key={item}>{item}</li>)}</ul></section><section><h4>Prepare</h4><ul>{scheme.documents.map(item=><li key={item}>{item}</li>)}</ul></section><section><h4>Access path</h4><ol>{scheme.accessSteps.map(item=><li key={item}>{item}</li>)}</ol></section></div><p><b>Limitation:</b> {scheme.limitation}</p></details><div className="scheme-source"><small>Source checked {scheme.sourceChecked}</small><a href={scheme.sourceUrl} target="_blank" rel="noreferrer">Open evidence ↗</a>{scheme.applyUrl&&<a className="scheme-apply" href={scheme.applyUrl} target="_blank" rel="noreferrer">Open official application doorway ↗</a>}</div></article>)}</div>{!shown.length&&<div className="registry-empty"><b>No verified seed match.</b><p>This does not mean no programme exists. Broaden the filters or use the official state scheme finder.</p></div>}
    </section>
  </>;
}
