/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { airMetrics, auditRecords, missingTransportLayers, railMetrics, roadMetrics, type TransportMetric } from "../../lib/infrastructure";

export const metadata:Metadata={title:"Transport & infrastructure evidence — India Evidence Dashboard",description:"Source-linked roads, tolls, NHAI finance, railways, aviation and transport audit evidence."};

function MetricGrid({metrics}:{metrics:TransportMetric[]}){return <div className="transport-metrics">{metrics.map((metric)=><article key={metric.label}><span>{metric.period}</span><h3>{metric.label}</h3><strong>{metric.value}</strong><p><b>Definition:</b> {metric.definition}</p><p><b>Limit:</b> {metric.limitation}</p><a href={metric.sourceUrl} target="_blank" rel="noreferrer">{metric.sourceLabel} ↗</a></article>)}</div>}

export default function InfrastructurePage(){return <main className="transport-shell">
  <header className="record-header"><a className="record-brand" href="/"><span className="brand-mark"/><b>India Evidence <em>Dashboard</em></b></a><nav><a href="#roads">Roads & tolls</a><a href="#rail">Railways</a><a href="#air">Airways</a><a href="#audits">Audits</a><a href="/infrastructure/registry">Registry</a></nav><a className="record-compare" href="/explore">All states</a></header>
  <section className="transport-hero"><p className="eyebrow">Transport & infrastructure ledger</p><h1>Built, financed, charged—and audited.</h1><p>Construction is not maintenance. A toll collection is not proof of fraud. A government release is not an audit. This room keeps each layer separate so a public claim can be tested against contracts, accounts, service outcomes and independent findings.</p><div><a href="/infrastructure/registry">Explore tolls & projects →</a><a href="#audits">See verified audit findings →</a></div></section>
  <aside className="transport-rule"><b>Neutral language rule</b><p>The dashboard does not label tolls “scams.” It records the rate notification, concession, construction status, collection, complaint and authoritative audit/court outcome. Where CAG found excess burden or control failure, the exact audited scope and amount are shown.</p></aside>
  <section className="transport-section" id="roads"><div className="transport-head"><div><p className="eyebrow">Roads, NHAI & tolls</p><h2>Follow the money and the road.</h2></div><p>National totals first. The new registry adds verified plaza and corridor examples while clearly showing incomplete coverage.</p></div><MetricGrid metrics={roadMetrics}/><a className="transport-registry-link" href="/infrastructure/registry">Open the verified toll & project registry <span>8 plazas · 8 projects →</span></a><div className="toll-proof-chain"><h3>What a toll-plaza record must prove</h3>{["Legal rate notification","Project and concession agreement","Commercial-operation and completion status","Applicable length and structures","Daily/monthly collection and remittance","Maintenance obligation and inspection","Complaints, refunds and resolution","CAG, court or authority finding"].map((item,index)=><span key={item}><i>{String(index+1).padStart(2,"0")}</i>{item}</span>)}</div></section>
  <section className="transport-section transport-rail" id="rail"><div className="transport-head"><div><p className="eyebrow">Railways</p><h2>Network, service, renewal and safety.</h2></div><p>Route kilometres, passenger journeys, freight, track renewals and accidents answer different questions.</p></div><MetricGrid metrics={railMetrics}/></section>
  <section className="transport-section" id="air"><div className="transport-head"><div><p className="eyebrow">Airways & airports</p><h2>Coverage is not the same as service.</h2></div><p>Airport activation, awarded routes, operating flights, passengers, subsidy, fares and reliability must remain separate.</p></div><MetricGrid metrics={airMetrics}/><div className="source-gap-banner"><b>Still source-mapped, not yet numeric</b><span>Airport-wise traffic</span><span>Flight delays and cancellations</span><span>Passenger complaints and refunds</span><span>Airfares and route competition</span><span>Safety occurrences</span><a href="https://www.aai.aero/en/business-opportunities/aai-traffic-news" target="_blank" rel="noreferrer">AAI monthly traffic doorway ↗</a></div></section>
  <section className="transport-section audit-section" id="audits"><div className="transport-head"><div><p className="eyebrow">Audit & accountability register</p><h2>Findings, not slogans.</h2></div><p>Each statement is bounded to the institution, project sample and period examined.</p></div><div className="audit-ledger">{auditRecords.map((record)=><article key={record.title}><span>{record.mode}</span><b>{record.status}</b><h3>{record.title}</h3><small>{record.period}</small><p>{record.finding}</p><a href={record.sourceUrl} target="_blank" rel="noreferrer">Open CAG record ↗</a></article>)}</div></section>
  <section className="transport-section missing-section" id="missing"><div className="transport-head"><div><p className="eyebrow">What was still missing</p><h2>The complete transport model.</h2></div><p>These are the next evidence tables—not decorative future features.</p></div><div className="missing-grid">{missingTransportLayers.map(([title,detail])=><article key={title}><h3>{title}</h3><p>{detail}</p><span>Source mapping required</span></article>)}</div></section>
  <footer className="record-footer"><a href="/">← National dashboard</a><a href="/explore">All states and UTs</a><a href="/#methodology">Methodology</a></footer>
  </main>}
