import type { Metadata } from "next";
import Link from "next/link";
import IndependenceClient from "./independence-client";

export const metadata:Metadata={title:"80th Independence Day — Where does India stand?",description:"Source-linked evidence on caste atrocities, women's and girls' safety, education and the limits of official data."};

const ncrbWomen="https://www.data.gov.in/resource/crime-head-wise-and-stateut-wise-indian-penal-code-ipc-crimes-and-special-and-local-laws";
const udise="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2282141&lang=1&reg=48";

export default function IndependenceDayPage(){return <main className="id-shell">
  <header className="record-header"><Link className="record-brand" href="/"><span className="brand-mark"/><b>India Evidence <em>Dashboard</em></b></Link><nav><a href="#answer">Direction</a><a href="#girls">Girls</a><a href="#caste">Caste</a><a href="#states">All states</a><a href="#gaps">Data gaps</a></nav><Link className="record-compare" href="/">National view</Link></header>
  <section className="id-hero"><div className="id-flag" role="img" aria-label="Indian tricolour"><i/><span>✺</span><b/></div><p className="eyebrow">15 August 2026 · 79 years completed</p><h1>Happy 80th<br/><span>Independence Day.</span></h1><p>After eight decades, where are we—and is India moving in a better direction or a worse one?</p><a href="#answer">See what the evidence can actually say ↓</a></section>
  <section className="id-answer" id="answer"><div><p className="eyebrow">The honest answer</p><h2>Progress exists.<br/><span>So does unacceptable harm.</span></h2></div><div className="id-answer-grid"><article className="is-progress"><b>BETTER</b><strong>Girls’ school participation, facilities and secondary retention improved.</strong><p>These are administrative national indicators—not proof that every girl has equal access or receives quality education.</p></article><article className="is-warning"><b>WORSE / UNRESOLVED</b><strong>Police-registered atrocities against SCs and STs increased between 2021 and 2023.</strong><p>Registration counts cannot by themselves establish whether prevalence, reporting or police recording drove the change.</p></article><article><b>STILL SEVERE</b><strong>Violence against women and girls remains visible across multiple official systems.</strong><p>No single number captures safety. Police records, surveys, court disposal and service access answer different questions.</p></article></div></section>
  <section className="id-numbers" id="girls"><div className="id-section-head"><div><p className="eyebrow">Women and girls · national evidence</p><h2>Safety cannot be reduced to one statistic.</h2></div><p>NCRB 2023 measures registered cases. NFHS measures survey-reported experience and prevalence. UDISE+ measures schools and enrolment.</p></div><div className="id-metric-grid">
    <article className="critical"><span>Crimes against women</span><strong>4,48,211</strong><b>NCRB 2023 · registered cases</b><p>About 1,228 registrations per day, derived from the annual total—not a live counter and not true prevalence.</p><a href={ncrbWomen}>Official table ↗</a></article>
    <article className="critical"><span>Girl-child POCSO</span><strong>66,232</strong><b>NCRB 2023 · registered cases</b><p>The table identifies girl-child victims only. Case counts and victim counts are distinct columns.</p><a href={ncrbWomen}>Official table ↗</a></article>
    <article className="critical"><span>Rape</span><strong>29,670</strong><b>NCRB 2023 · registered cases</b><p>About 81 registrations per day as a derived annual average; under-reporting means this is not prevalence.</p><a href={ncrbWomen}>Official table ↗</a></article>
    <article><span>Cruelty by husband / relatives</span><strong>1,33,676</strong><b>Section 498A IPC · NCRB 2023</b><p>Police-registered incidence under the cited legal category.</p><a href={ncrbWomen}>Official table ↗</a></article>
    <article><span>Dowry deaths</span><strong>6,156</strong><b>Section 304B IPC · NCRB 2023</b><p>A narrowly defined registered offence—not every gender-linked death.</p><a href={ncrbWomen}>Official table ↗</a></article>
    <article><span>Spousal violence</span><strong>29.3%</strong><b>NFHS-5 · 2019–21</b><p>Ever-married women aged 18–49 reporting ever experiencing physical and/or sexual spousal violence.</p><a href="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2245904&lang=1&reg=3">Official survey summary ↗</a></article>
    <article><span>Child marriage</span><strong>23.3%</strong><b>NFHS-5 · women aged 20–24</b><p>Share married before age 18; down from 26.8% in NFHS-4, but still nearly one in four.</p><a href="https://www.mohfw.gov.in/sites/default/files/Publication%20Health%20and%20Family%20Welfare%20Statistics%20in%20India%202023.pdf">MoHFW state table ↗</a></article>
    <article className="progress"><span>Girls’ enrolment share</span><strong>48.4%</strong><b>UDISE+ 2025–26</b><p>Up from 48.0% in 2022–23. This is participation among enrolled students, not the share of all girls attending school.</p><a href={udise}>Official release ↗</a></article>
    <article className="warning"><span>Secondary retention</span><strong>51.9%</strong><b>UDISE+ 2025–26</b><p>Improved from 44.1% in 2022–23, yet roughly half the cohort is retained through the source-defined secondary cycle.</p><a href={udise}>Official release ↗</a></article>
    <article className="progress"><span>Schools with girls’ toilets</span><strong>98.5%</strong><b>UDISE+ 2025–26</b><p>Reported facility availability does not prove functionality, privacy, water access or daily usability.</p><a href={udise}>Official release ↗</a></article>
    <article className="warning"><span>POSH · new SHe-Box portal</span><strong>9</strong><b>19 Oct–29 Nov 2024 · complaints received</b><p>This was an early count after complaint registration went live on the revamped portal. It is not the total handled by every employer Internal Committee or Local Committee in India.</p><a href="https://sansad.in/getFile/debatestextmk/18/III/pdf%2029.11.2024.pdf?source=loksabhadocs">Lok Sabha record ↗</a></article>
  </div></section>
  <section className="id-caste" id="caste"><div><p className="eyebrow">Caste and tribal atrocities</p><h2>Registered harm rose.<br/>Interpret carefully.</h2><p>NCRB defines “atrocities” against SCs as offences by non-SCs/STs under the cited statutory frame. The ST series uses its corresponding legal and population definitions.</p></div><div className="id-trend-grid"><article><span>Crimes / atrocities against SCs</span><div><b>50,900<small>2021</small></b><i>→</i><b>57,789<small>2023</small></b></div><strong>+13.5%</strong><p>Police-registered cases; 2023 rate 28.7 per lakh SC population and chargesheeting rate 81.2%.</p><a href="https://www.data.gov.in/resource/stateut-wise-crimeatrocities-against-scheduled-castes-2021-2023">Official NCRB table ↗</a></article><article><span>Crimes / atrocities against STs</span><div><b>8,802<small>2021</small></b><i>→</i><b>12,960<small>2023</small></b></div><strong>+47.2%</strong><p>Police-registered cases; 2023 rate 12.4 per lakh ST population and chargesheeting rate 79.5%.</p><a href="https://www.data.gov.in/resource/stateut-wise-crimeatrocities-against-scheduled-tribes-2021-2023">Official NCRB table ↗</a></article></div></section>
  <IndependenceClient/>
  <section className="id-gaps" id="gaps"><div><p className="eyebrow">What India still does not measure cleanly</p><h2>A missing category is itself evidence.</h2></div><div><article><b>All-India POSH / ICC total</b><p>No complete current public aggregate covers complaints handled by every workplace Internal Committee and Local Committee. A parliamentary committee recommended annual national publication; this dashboard therefore does not turn SHe-Box portal traffic into an all-workplace total.</p><a href="https://sansad.in/getFile/rsnew/Committee_site/Committee_File/ReportFile/16/198/365_2025_6_17.pdf?source=rajyasabha">Read the committee recommendation ↗</a></article><article><b>Racism / ethnicity</b><p>NCRB does not publish one nationwide “racism crime” category. Relevant offences are dispersed across IPC/SLL, state police and protections for particular communities.</p></article><article><b>Fascism</b><p>“Fascism” is a political interpretation, not a police crime classification. Track measurable components instead: unlawful violence, hate speech, custodial harm, press freedom, protest restrictions and court findings.</p></article><article><b>Caste discrimination outside FIRs</b><p>Atrocity cases do not capture every exclusion in housing, work, schools, healthcare, temples, social networks or local institutions.</p></article><article><b>Unreported gender violence</b><p>Police registrations are a lower-bound administrative record, not a survey of every incident. Fear, stigma, access and police practice affect reporting.</p></article></div></section>
  <section className="id-video"><p className="eyebrow">For the Independence Day video</p><blockquote>“India is not moving in only one direction. Girls’ education has improved. Infrastructure has improved. But freedom is unfinished when caste atrocities rise, nearly one in four young women was married before eighteen, and hundreds of thousands of crimes against women are registered in a year. Patriotism is not hiding the evidence. Patriotism is refusing to accept that this is enough.”</blockquote><p>Use the source year aloud. Say “registered cases,” not “actual crimes.” Say “survey prevalence,” not “police data,” for NFHS figures.</p></section>
  <footer className="record-footer"><Link href="/">← National dashboard</Link><Link href="/history">Freedom movement archive</Link><Link href="/state-packs">State evidence packs</Link><Link href="/corrections">Challenge a record</Link></footer>
</main>}
