"use client";

import { FormEvent, useState } from "react";

export default function CorrectionForm(){
  const [recordId,setRecordId]=useState(""); const [requestText,setRequestText]=useState(""); const [supportingUrl,setSupportingUrl]=useState(""); const [attestation,setAttestation]=useState(false); const [status,setStatus]=useState<{kind:"idle"|"sending"|"success"|"error";message?:string;receipt?:string}>({kind:"idle"});
  async function submit(event:FormEvent){event.preventDefault();setStatus({kind:"sending"});try{const response=await fetch("/api/corrections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recordId,requestText,supportingUrl,attestation})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed.");setStatus({kind:"success",message:"Correction request stored in the editorial queue.",receipt:data.receipt});setRecordId("");setRequestText("");setSupportingUrl("");setAttestation(false);}catch(error){setStatus({kind:"error",message:error instanceof Error?error.message:"The request could not be sent."});}}
  return <form className="correction-form" onSubmit={submit}><div><p className="eyebrow">Privacy-minimised submission</p><h2>Request an evidence review</h2><p>No contact field is collected. Keep the receipt shown after submission.</p></div><label>Evidence record ID <span>optional</span><input value={recordId} onChange={(event)=>setRecordId(event.target.value)} maxLength={160} placeholder="Example: nhai-project-…" autoComplete="off"/></label><label>What should be corrected? <span>{requestText.length}/3,000</span><textarea value={requestText} onChange={(event)=>setRequestText(event.target.value)} minLength={30} maxLength={3000} required placeholder="Name the current statement, the correction, the relevant period and why the cited definition or source supports the change."/></label><label>Supporting public source <span>optional · HTTPS only</span><input type="url" inputMode="url" value={supportingUrl} onChange={(event)=>setSupportingUrl(event.target.value)} maxLength={1200} placeholder="https://official-source.example/report"/></label><label className="correction-check"><input type="checkbox" checked={attestation} onChange={(event)=>setAttestation(event.target.checked)} required/><span>I have excluded personal data and understand that submission does not change the public record automatically.</span></label><button disabled={status.kind==="sending"}>{status.kind==="sending"?"Recording securely…":"Submit correction request"}</button>{status.kind!=="idle"&&status.kind!=="sending"&&<div className={`correction-status ${status.kind}`} role="status"><strong>{status.message}</strong>{status.receipt&&<><span>Receipt</span><code>{status.receipt}</code></>}</div>}</form>;
}
