export type EvidenceCadence = "live connector" | "monthly" | "quarterly" | "annual" | "release cycle" | "event based";
export type EvidenceCoverage = "loaded" | "connected" | "source mapped" | "editorial queue" | "data gap";

export type EvidenceDomain = {
  id: string;
  group: string;
  label: string;
  coverage: EvidenceCoverage;
  cadence: EvidenceCadence;
  geography: string;
  definition: string;
  limitation: string;
  sourceTitle: string;
  sourceUrl: string;
  route?: string;
};

const domain = (item: EvidenceDomain) => item;

export const evidenceCatalog: EvidenceDomain[] = [
  domain({id:"state-output",group:"Economy",label:"GDP, GSDP and NSDP",coverage:"loaded",cadence:"annual",geography:"India and state/UT",definition:"National production and state domestic-product series at current or constant prices.",limitation:"GDP, GSDP and NSDP are not interchangeable; source year and price basis must match.",sourceTitle:"MoSPI and RBI state statistics",sourceUrl:"https://www.rbi.org.in/Scripts/PublicationsView.aspx?id=22483",route:"/compare"}),
  domain({id:"income-person",group:"Economy",label:"Per-capita state income",coverage:"loaded",cadence:"annual",geography:"State/UT",definition:"Per-capita NSDP at the source publication's stated price basis.",limitation:"An average is not median salary, disposable income or household wealth.",sourceTitle:"RBI Handbook of Statistics on Indian States",sourceUrl:"https://www.rbi.org.in/Scripts/PublicationsView.aspx?id=22483",route:"/compare"}),
  domain({id:"inflation",group:"Economy",label:"Consumer price inflation",coverage:"source mapped",cadence:"monthly",geography:"India and available state/UT",definition:"Change in CPI for a defined rural, urban or combined consumption basket.",limitation:"Base year, basket and geography must match before comparison.",sourceTitle:"MoSPI CPI releases",sourceUrl:"https://www.mospi.gov.in/"}),
  domain({id:"employment",group:"Economy",label:"Jobs, unemployment and labour participation",coverage:"source mapped",cadence:"quarterly",geography:"India and state/UT where published",definition:"PLFS employment status, labour-force participation and unemployment measures.",limitation:"Usual-status and current-weekly-status estimates answer different questions.",sourceTitle:"MoSPI Periodic Labour Force Survey",sourceUrl:"https://www.mospi.gov.in/publication/plfs"}),
  domain({id:"poverty-wealth",group:"Economy",label:"Poverty, consumption and wealth distribution",coverage:"editorial queue",cadence:"release cycle",geography:"India and limited state estimates",definition:"Separate official consumption/poverty measures from attributable research wealth estimates.",limitation:"Research estimates are not official administrative counts and methodology changes matter.",sourceTitle:"MoSPI household consumption surveys",sourceUrl:"https://www.mospi.gov.in/"}),
  domain({id:"investment-trade",group:"Economy",label:"Investment, industry, exports and trade",coverage:"source mapped",cadence:"quarterly",geography:"India and available state/UT",definition:"FDI equity inflow, industrial output, exports and capital formation remain separate measures.",limitation:"No composite 'investment return' rank is defensible across countries or states.",sourceTitle:"DPIIT FDI statistics",sourceUrl:"https://dpiit.gov.in/publications/fdi-statistics"}),
  domain({id:"budgets",group:"Public finance",label:"Union and state budgets",coverage:"source mapped",cadence:"annual",geography:"India and state/UT",definition:"Budget estimate, revised estimate and audited actual expenditure stored separately.",limitation:"An allocation does not prove expenditure or delivery.",sourceTitle:"CAG state accounts and finance accounts",sourceUrl:"https://cag.gov.in/en/state-accounts-report"}),
  domain({id:"debt",group:"Public finance",label:"Debt, liabilities and guarantees",coverage:"source mapped",cadence:"annual",geography:"India and state/UT",definition:"Outstanding liabilities, debt-to-output, interest burden and disclosed guarantees.",limitation:"Book-value assets are not the market value of all public property.",sourceTitle:"RBI State Finances",sourceUrl:"https://www.rbi.org.in/Scripts/AnnualPublications.aspx?head=State%20Finances%20:%20A%20Study%20of%20Budgets"}),
  domain({id:"tax",group:"Public finance",label:"Tax revenue and fiscal transfers",coverage:"editorial queue",cadence:"monthly",geography:"India and state/UT",definition:"Own-tax revenue, GST receipts, devolution and grants shown as distinct flows.",limitation:"Gross collections, settlements and final accounts differ.",sourceTitle:"GST statistics",sourceUrl:"https://www.gst.gov.in/"}),
  domain({id:"sector-spend",group:"Public finance",label:"Sector spending and outcomes",coverage:"editorial queue",cadence:"annual",geography:"India and state/UT",definition:"Comparable expenditure by health, education, infrastructure, welfare and other functions.",limitation:"Spend does not alone establish quality, coverage or impact.",sourceTitle:"Open Government Data budget catalogues",sourceUrl:"https://www.data.gov.in/"}),
  domain({id:"audit-procurement",group:"Public finance",label:"Audits, procurement and project escalation",coverage:"source mapped",cadence:"release cycle",geography:"India, state/UT and project",definition:"CAG findings, tender records, contract changes, delays and cost escalation.",limitation:"A delay or audit observation is not automatically fraud or a criminal finding.",sourceTitle:"Comptroller and Auditor General of India",sourceUrl:"https://cag.gov.in/"}),
  domain({id:"population",group:"People",label:"Population and migration",coverage:"source mapped",cadence:"release cycle",geography:"India, state/UT and district",definition:"Census population, official projections and migration measures labelled separately.",limitation:"A projection is not a census count.",sourceTitle:"Census of India",sourceUrl:"https://censusindia.gov.in/"}),
  domain({id:"vital-statistics",group:"People",label:"Births, deaths and fertility",coverage:"source mapped",cadence:"annual",geography:"India and state/UT",definition:"Birth rate, death rate, fertility and registered vital events using SRS/CRS definitions.",limitation:"Registration completeness and survey estimates differ.",sourceTitle:"Census SRS and CRS",sourceUrl:"https://censusindia.gov.in/census.website/en/node/294"}),
  domain({id:"gender-ratio",group:"People",label:"Sex ratio at birth and child sex ratio",coverage:"source mapped",cadence:"annual",geography:"India and state/UT",definition:"Girls per 1,000 boys under the cited SRS, CRS or Census definition.",limitation:"No invented 'foetus killing rate'; PCPNDT enforcement is a separate legal series.",sourceTitle:"Census vital statistics",sourceUrl:"https://censusindia.gov.in/"}),
  domain({id:"schools",group:"Education",label:"Schools, enrolment, teachers and locations",coverage:"source mapped",cadence:"annual",geography:"State/UT, district and school where released",definition:"Recognised institutions, enrolment, teachers, infrastructure and retention indicators.",limitation:"School count, management type, recognition and reporting year must match.",sourceTitle:"UDISE+",sourceUrl:"https://dashboard.udiseplus.gov.in/"}),
  domain({id:"learning",group:"Education",label:"Learning outcomes and higher education",coverage:"editorial queue",cadence:"release cycle",geography:"India and state/UT",definition:"Assessment results and higher-education enrolment kept separate from school inputs.",limitation:"Assessments with different samples or instruments are not directly comparable.",sourceTitle:"Ministry of Education statistics",sourceUrl:"https://www.education.gov.in/statistics-new"}),
  domain({id:"health-capacity",group:"Health",label:"Hospitals, facilities and beds",coverage:"source mapped",cadence:"annual",geography:"State/UT and facility where released",definition:"Sanctioned, functional and in-position capacity stored as separate fields.",limitation:"Published capacity is not real-time vacant-bed availability.",sourceTitle:"MoHFW Health Dynamics of India",sourceUrl:"https://www.mohfw.gov.in/"}),
  domain({id:"health-outcomes",group:"Health",label:"Mortality, morbidity and public-health outcomes",coverage:"source mapped",cadence:"release cycle",geography:"India and state/UT",definition:"Maternal, infant, neonatal and disease indicators using each publication's denominator.",limitation:"Reporting and estimation systems differ; a case count is not prevalence.",sourceTitle:"MoHFW and Census SRS",sourceUrl:"https://www.mohfw.gov.in/"}),
  domain({id:"ambulances",group:"Health",label:"Ambulances and emergency-response capacity",coverage:"data gap",cadence:"release cycle",geography:"State/UT and programme",definition:"Sanctioned, deployed, active and available vehicles treated as different measures.",limitation:"No verified nationwide real-time fleet-availability feed is connected.",sourceTitle:"National Health Mission",sourceUrl:"https://nhm.gov.in/"}),
  domain({id:"water-sanitation",group:"Basic services",label:"Drinking water and sanitation",coverage:"source mapped",cadence:"release cycle",geography:"State/UT, district and village where released",definition:"Reported connections, service level, quality and functionality kept separate.",limitation:"A reported connection does not prove continuous safe supply.",sourceTitle:"Jal Jeevan Mission reports",sourceUrl:"https://ejalshakti.gov.in/jjmreport/JJMIndia.aspx"}),
  domain({id:"electricity-energy",group:"Basic services",label:"Electricity, energy mix and reliability",coverage:"editorial queue",cadence:"monthly",geography:"India and state/UT",definition:"Connections, generation, demand, outages and renewable capacity remain distinct.",limitation:"Installed capacity is not actual generation or reliable household service.",sourceTitle:"Central Electricity Authority",sourceUrl:"https://cea.nic.in/"}),
  domain({id:"food-welfare",group:"Basic services",label:"Food security and social protection",coverage:"source mapped",cadence:"monthly",geography:"India and state/UT",definition:"Eligible households, allocations, offtake and delivery are separate evidence stages.",limitation:"Allocation does not prove receipt by every eligible person.",sourceTitle:"Department of Food and Public Distribution",sourceUrl:"https://dfpd.gov.in/"}),
  domain({id:"registered-crime",group:"Safety and justice",label:"Registered crime and crimes against women",coverage:"connected",cadence:"annual",geography:"State/UT",definition:"Police-registered cases, rates and charge-sheeting using NCRB definitions.",limitation:"Registered cases are not estimated prevalence and reporting propensity differs.",sourceTitle:"NCRB through data.gov.in",sourceUrl:"https://www.data.gov.in/",route:"/explore"}),
  domain({id:"crime-detail",group:"Safety and justice",label:"Violent, cyber, child, caste and trafficking offences",coverage:"editorial queue",cadence:"annual",geography:"State/UT",definition:"Offence-specific registered series with law, year and denominator visible.",limitation:"Legal categories and reporting practices can change across years.",sourceTitle:"National Crime Records Bureau",sourceUrl:"https://ncrb.gov.in/"}),
  domain({id:"police-prisons",group:"Safety and justice",label:"Police strength, vacancies and prisons",coverage:"source mapped",cadence:"annual",geography:"State/UT",definition:"Sanctioned and actual police personnel, prison population, capacity and occupancy.",limitation:"Headcount does not measure policing quality or individual guilt.",sourceTitle:"Bureau of Police Research and Development",sourceUrl:"https://bprd.nic.in/"}),
  domain({id:"courts",group:"Safety and justice",label:"Courts, pendency and legal services",coverage:"source mapped",cadence:"monthly",geography:"Court, district and state/UT",definition:"Institution, disposal and pendency measures from judicial systems.",limitation:"Pendency is affected by case mix, vacancies and procedural differences.",sourceTitle:"National Judicial Data Grid",sourceUrl:"https://njdg.ecourts.gov.in/"}),
  domain({id:"road-safety",group:"Safety and justice",label:"Road accidents, deaths and injuries",coverage:"connected",cadence:"annual",geography:"State/UT",definition:"Reported annual incidents, deaths and injuries; daily figures are labelled derived averages.",limitation:"Annual average is not a live daily incident feed.",sourceTitle:"MoRTH through data.gov.in",sourceUrl:"https://www.data.gov.in/",route:"/explore"}),
  domain({id:"disasters",group:"Safety and justice",label:"Disasters, relief and official response",coverage:"editorial queue",cadence:"event based",geography:"India, state/UT and district",definition:"Hazard, warning, impact, relief allocation, delivery and audit evidence kept separate.",limitation:"Early casualty estimates and final official records may differ.",sourceTitle:"National Disaster Management Authority",sourceUrl:"https://ndma.gov.in/"}),
  domain({id:"roads-tolls",group:"Infrastructure",label:"Roads, NHAI projects and tolls",coverage:"loaded",cadence:"release cycle",geography:"State/UT, corridor and plaza",definition:"Project scope, milestones, cost, concession, fee notification, collection and audit evidence.",limitation:"A toll or delay is not labelled a scam without authoritative findings.",sourceTitle:"NHAI and MoRTH",sourceUrl:"https://nhai.gov.in/",route:"/infrastructure/registry"}),
  domain({id:"rail",group:"Infrastructure",label:"Railways, stations and safety",coverage:"source mapped",cadence:"annual",geography:"Zone, division, station and project",definition:"Capital projects, operations, passenger/freight metrics and safety events.",limitation:"Railway geography does not map cleanly to state boundaries.",sourceTitle:"Indian Railways statistical publications",sourceUrl:"https://indianrailways.gov.in/",route:"/infrastructure#rail"}),
  domain({id:"aviation",group:"Infrastructure",label:"Airports, aviation traffic and connectivity",coverage:"source mapped",cadence:"monthly",geography:"Airport and state/UT",definition:"Airport projects, passengers, cargo, routes and safety records.",limitation:"Passenger volume is not a measure of affordability or service quality.",sourceTitle:"Airports Authority of India",sourceUrl:"https://www.aai.aero/",route:"/infrastructure#aviation"}),
  domain({id:"ports-transit",group:"Infrastructure",label:"Ports, waterways and urban transport",coverage:"editorial queue",cadence:"monthly",geography:"Port, waterway, city and project",definition:"Capacity, traffic, capital project and service evidence separated by mode.",limitation:"Capacity and actual throughput are not interchangeable.",sourceTitle:"Ministry of Ports, Shipping and Waterways",sourceUrl:"https://shipmin.gov.in/"}),
  domain({id:"housing-urban",group:"Infrastructure",label:"Housing, cities and local infrastructure",coverage:"source mapped",cadence:"release cycle",geography:"State/UT and urban local body",definition:"Sanctions, starts, completions, occupancy and service outcomes remain separate.",limitation:"Sanctioned or geo-tagged units do not automatically prove occupied delivery.",sourceTitle:"Ministry of Housing and Urban Affairs",sourceUrl:"https://mohua.gov.in/"}),
  domain({id:"agriculture",group:"Agriculture",label:"Agriculture, crops, irrigation and farm support",coverage:"source mapped",cadence:"release cycle",geography:"India, state/UT and district",definition:"Area, output, yield, prices, procurement, irrigation and support payments.",limitation:"Production, farmer income and procurement benefit are different measures.",sourceTitle:"Directorate of Economics and Statistics",sourceUrl:"https://desagri.gov.in/"}),
  domain({id:"forest",group:"Environment",label:"Forest and tree cover",coverage:"loaded",cadence:"release cycle",geography:"India and state/UT",definition:"Satellite-assessed forest and tree cover under the report's definitions.",limitation:"Tree cover is not biodiversity, legal forest status or continuous monitoring.",sourceTitle:"Forest Survey of India",sourceUrl:"https://fsi.nic.in/forest-report-2023"}),
  domain({id:"air",group:"Environment",label:"Air pollution",coverage:"connected",cadence:"live connector",geography:"Monitoring station",definition:"Station pollutant observations and source-reported averages.",limitation:"A station is not a statewide average or personal-exposure measure.",sourceTitle:"CPCB through data.gov.in",sourceUrl:"https://www.data.gov.in/resource/real-time-air-quality-index-various-locations",route:"/#live-data"}),
  domain({id:"water-pollution",group:"Environment",label:"Water quality, waste and pollution",coverage:"editorial queue",cadence:"release cycle",geography:"Station, city, river and state/UT",definition:"Monitoring observations, waste generation/treatment and compliance evidence.",limitation:"Sparse monitoring cannot establish continuous statewide conditions.",sourceTitle:"Central Pollution Control Board",sourceUrl:"https://cpcb.nic.in/"}),
  domain({id:"climate-weather",group:"Environment",label:"Weather, warnings and climate risk",coverage:"connected",cadence:"live connector",geography:"Reference grid; official warnings not connected",definition:"Current public model conditions kept separate from official IMD warnings and climate normals.",limitation:"Open-Meteo is model data, not an official Indian emergency-warning service.",sourceTitle:"Open-Meteo documentation",sourceUrl:"https://open-meteo.com/en/docs",route:"/#live-data"}),
  domain({id:"representatives",group:"Governance",label:"Representatives, elections and constituencies",coverage:"source mapped",cadence:"event based",geography:"Constituency and state/UT",definition:"Election results, constituency context and declared candidate information.",limitation:"Allegations and pending cases require exact affidavit/court context; no guilt is implied.",sourceTitle:"Election Commission of India",sourceUrl:"https://www.eci.gov.in/"}),
  domain({id:"promises",group:"Governance",label:"Public commitments and promises",coverage:"editorial queue",cadence:"event based",geography:"India, state/UT and issuing body",definition:"Official commitment, baseline, target, deadline, dated evidence and assessment rationale.",limitation:"No party score and no verdict without a complete evidence chain.",sourceTitle:"India Evidence methodology",sourceUrl:"/#methodology"}),
  domain({id:"schemes-loans",group:"Governance",label:"Schemes, subsidies and loan access",coverage:"loaded",cadence:"release cycle",geography:"India with jurisdiction applicability",definition:"Eligibility, support, lender/agency route, documents and verified application doorway.",limitation:"A directory is not approval, financial advice or proof of benefit delivery.",sourceTitle:"Official scheme and lender doorways",sourceUrl:"https://www.myscheme.gov.in/",route:"/schemes"}),
  domain({id:"grievance-rti",group:"Governance",label:"Grievances, RTI and correction pathways",coverage:"loaded",cadence:"event based",geography:"India and authority",definition:"Official filing doorways plus a privacy-minimised dashboard correction request.",limitation:"The dashboard cannot compel an authority or replace statutory filing.",sourceTitle:"CPGRAMS and RTI Online",sourceUrl:"https://pgportal.gov.in/",route:"/corrections"}),
  domain({id:"local-government",group:"Governance",label:"Local government and civic services",coverage:"source mapped",cadence:"release cycle",geography:"District, panchayat and urban local body",definition:"Administrative directory, finances, services and local plan evidence.",limitation:"Administrative boundaries and codes change over time.",sourceTitle:"Local Government Directory",sourceUrl:"https://lgdirectory.gov.in/"}),
  domain({id:"digital-access",group:"Governance",label:"Digital access and telecommunications",coverage:"source mapped",cadence:"quarterly",geography:"India and service area",definition:"Subscriptions, broadband, coverage and service-quality indicators.",limitation:"Subscriber density does not prove meaningful or affordable access.",sourceTitle:"TRAI performance indicators",sourceUrl:"https://www.trai.gov.in/release-publication/reports/performance-indicators-reports"}),
  domain({id:"freedom-movement",group:"Historical record",label:"Freedom movement people, documents and disputes",coverage:"loaded",cadence:"release cycle",geography:"India, districts and undivided India",definition:"Person- and event-level dossiers separate documented actions, attributed interpretations and unresolved evidence gaps.",limitation:"Four source-linked starting dossiers are not a complete freedom-fighter registry or final historical verdict.",sourceTitle:"National Archives and Ministry of Culture repositories",sourceUrl:"https://www.nationalarchives.nic.in/en/online-records-national-archives-india/netaji-papers",route:"/history"}),
  domain({id:"historical-crisis",group:"Historical record",label:"1947–present policy and crisis timeline",coverage:"editorial queue",cadence:"event based",geography:"India and state/UT",definition:"Dated laws, governments, crises, response, relief and outcome evidence by decade.",limitation:"One validation anchor per decade is not complete historical coverage.",sourceTitle:"Legislative Department and public archives",sourceUrl:"https://legislative.gov.in/constitution-of-india/",route:"/#timeline"}),
];

export const catalogGroups = [...new Set(evidenceCatalog.map((item) => item.group))];

export const catalogCoverage = evidenceCatalog.reduce<Record<EvidenceCoverage, number>>((summary, item) => {
  summary[item.coverage] += 1;
  return summary;
}, {loaded:0, connected:0,"source mapped":0,"editorial queue":0,"data gap":0});
