export type FreedomRecord={id:string;name:string;state:string;district:string;period:string;movement:string;record:string;sourceUrl:string;sourceTitle:string;reviewNote:string};

export type CellularJailProvinceRecord={province:string;count:number;note?:string};

export const cellularJailSource={
  title:"Ministry of Culture — Rajya Sabha Unstarred Question No. 985",
  date:"13 February 2025",
  period:"1909–1938",
  url:"https://sansad.in/getFile/annex/267/AU985_1iedDF.pdf?source=pqars",
  definition:"Revolutionaries recorded by the Directorate of Art and Culture, Andaman & Nicobar Administration as jailed in Cellular Jail from 1909 to 1938, grouped by the province/state labels printed in the parliamentary annexure.",
  limitation:"This is a Cellular Jail incarceration count, not a count of every participant in India's freedom struggle. Historical Bengal is undivided Bengal and must not be treated as present-day West Bengal alone."
} as const;

export const cellularJailProvinceRecords:CellularJailProvinceRecord[]=[
  {province:"Bengal",count:398,note:"Undivided Bengal; not present-day West Bengal alone"},
  {province:"Punjab",count:95},
  {province:"Maharashtra",count:3},
  {province:"Bihar",count:17},
  {province:"Uttar Pradesh",count:18},
  {province:"Kerala",count:14},
  {province:"Andhra Pradesh",count:8},
  {province:"Odisha",count:5},
  {province:"Himachal / NW Frontier / Tamil Nadu / state unknown",count:27,note:"Combined category as published; cannot be separated from this source"}
];

export const cellularJailTotal=cellularJailProvinceRecords.reduce((sum,item)=>sum+item.count,0);

export const freedomRecords:FreedomRecord[]=[
  {id:"velu-nachiyar",name:"Velu Nachiyar",state:"Tamil Nadu",district:"Ramanathapuram / Sivaganga",period:"c. 1730-1796",movement:"Early anti-colonial resistance",record:"The Ministry of Culture profile describes her alliance-building and armed campaign against the East India Company before the nineteenth-century mass movements.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?312=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official commemorative narrative; archival corroboration of individual episode details remains required."},
  {id:"kittur-rani-chennamma",name:"Kittur Rani Chennamma",state:"Karnataka",district:"Belagavi",period:"1778-1829",movement:"Kittur resistance",record:"The official profile records her armed opposition to British refusal to recognise Kittur's succession and her subsequent imprisonment at Bailhongal.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?188=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official commemorative profile based on a civil-service academy publication."},
  {id:"tirot-sing",name:"U Tirot Sing Syiem",state:"Meghalaya",district:"West Khasi Hills",period:"early nineteenth century-1835",movement:"Anglo-Khasi War",record:"The Ministry of Culture profile records his leadership against British expansion into the Khasi Hills, guerrilla resistance, capture and deportation to Dhaka.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?57=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official public narrative; event chronology should be paired with colonial and Khasi records."},
  {id:"veer-surendra-sai",name:"Veer Surendra Sai",state:"Odisha",district:"Sambalpur",period:"1809-1884",movement:"Sambalpur resistance and 1857",record:"The official record describes his claim in Sambalpur, imprisonment, release during 1857, guerrilla resistance, rearrest and detention at Asirgarh.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?1978=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Long-form official narrative; judicial and administrative documents remain separate source work."},
  {id:"peer-ali-khan",name:"Peer Ali Khan",state:"Bihar",district:"Patna",period:"c. 1812-1857",movement:"Revolt of 1857",record:"The Ministry of Culture profile records his role as a Patna bookseller involved in organising the July 1857 uprising and his execution by the colonial administration.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?328=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"The official narrative itself notes uncertainty about birthplace; that uncertainty is preserved."},
  {id:"birsa-munda",name:"Birsa Munda",state:"Jharkhand",district:"Khunti",period:"c. 1875-1900",movement:"Munda resistance",record:"The official repository links Birsa's leadership to resistance against British domination, records imprisonment in the 1890s and death in colonial custody in 1900.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?310=",sourceTitle:"Ministry of Culture - Digital District Repository",reviewNote:"Profile cites a Department of Posts publication; a fuller dossier needs land, police and prison records."},
  {id:"alluri-sitarama-raju",name:"Alluri Sitarama Raju",state:"Andhra Pradesh",district:"Visakhapatnam / Agency areas",period:"1897-1924",movement:"Rampa Rebellion",record:"The official repository connects his leadership of the 1922-24 Rampa Rebellion with tribal opposition to colonial forest restrictions.",sourceUrl:"https://amritmahotsav.nic.in/district-reopsitory-detail.htm?16=",sourceTitle:"Ministry of Culture - Digital District Repository",reviewNote:"Official commemorative profile; district boundaries and episode-level claims require archival indexing."},
  {id:"matangini-hazra",name:"Matangini Hazra",state:"West Bengal",district:"Paschim Medinipur",period:"1870-1942",movement:"Civil Disobedience and Quit India",record:"The official profile records her participation in Salt Act protests and the 1942 Tamluk procession in which British Indian police shot her.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?317=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official narrative; local parallel-government and police records require their own linked dossier."},
  {id:"rani-gaidinliu",name:"Rani Gaidinliu",state:"Manipur",district:"Tamenglong",period:"1915-1993",movement:"Heraka and Naga anti-colonial resistance",record:"The official profile records her joining the Heraka movement, arrest in 1932, life sentence and imprisonment across the Northeast until 1947.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?56=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"The movement's religious, political and later regional contexts need multiple community and archival sources."},
  {id:"kanaklata-barua",name:"Kanaklata Barua",state:"Assam",district:"Sonitpur",period:"1924-1942",movement:"Quit India",record:"The official profile records her participation in the 20 September 1942 procession to Gohpur police station and her death in police firing.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?347=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Profile cites a Department of Posts special cover; police and procession records remain to be indexed."},
  {id:"komaram-bheem",name:"Komaram Bheem",state:"Telangana",district:"Komaram Bheem Asifabad",period:"c. 1901-1940",movement:"Adivasi land and forest resistance",record:"The official profile records his mobilisation around Jal, Jangal, Jameen and armed resistance to the Hyderabad State administration.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?250=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"The cited basis is a Telangana school textbook; administrative, oral-history and community sources are still required."},
  {id:"subhas-chandra-bose",name:"Subhas Chandra Bose",state:"West Bengal",district:"Kolkata / international theatres",period:"1897-1945",movement:"Forward Bloc, Azad Hind Government and INA",record:"The National Archives provides a dedicated doorway to declassified Netaji papers, including files transferred from multiple Union government collections and INA/inquiry records.",sourceUrl:"https://www.nationalarchives.nic.in/en/online-records-national-archives-india/netaji-papers",sourceTitle:"National Archives of India - Netaji Papers",reviewNote:"This points to the primary file corpus; it does not resolve disputed death or alliance interpretations."}
];

export type DocumentRecord={id:string;title:string;person:string;date:string;documentType:string;publisher:string;url:string;whatItProves:string;whatItDoesNotProve:string};
export const documentRecords:DocumentRecord[]=[
  {id:"netaji-papers",title:"Netaji Papers",person:"Subhas Chandra Bose",date:"Declassified collections",documentType:"Official archive collection",publisher:"National Archives of India",url:"https://www.nationalarchives.nic.in/en/online-records-national-archives-india/netaji-papers",whatItProves:"That a defined government-held corpus has been declassified and made available through the archive doorway.",whatItDoesNotProve:"That every public claim about Bose, the INA or his death is established."},
  {id:"netaji-declassification",title:"Government reply on Netaji declassification",person:"Subhas Chandra Bose",date:"Government summary",documentType:"Parliamentary/PIB record",publisher:"Press Information Bureau",url:"https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1594556",whatItProves:"The reported number and originating departments of files transferred and uploaded.",whatItDoesNotProve:"The truth of every proposition contained inside those files."},
  {id:"savarkar-1913",title:"Reference to Savarkar's petition dated 14 November 1913",person:"V. D. Savarkar",date:"14 November 1913",documentType:"Parliamentary record",publisher:"Parliament of India",url:"https://sansad.in/getFile/loksabhaquestions/annex/173/AU4718.pdf?source=pqals",whatItProves:"That the official parliamentary record identifies a petition from the named convict and date.",whatItDoesNotProve:"A partisan verdict about motive, courage, strategy or betrayal."},
  {id:"mookerjee-letter-1950",title:"Nehru's letter to Syama Prasad Mookerjee",person:"Syama Prasad Mookerjee",date:"15 April 1950",documentType:"Published correspondence",publisher:"Nehru Archive / Selected Works",url:"https://nehruarchive.in/documents/to-syama-prasad-mookerjee-15-april-1950-v9jqq1",whatItProves:"The content and date of Nehru's stated position concerning Mookerjee's resignation.",whatItDoesNotProve:"That one correspondent's framing resolves every political dispute."},
  {id:"abhilekh-patal",title:"Abhilekh Patal archival search doorway",person:"Multiple",date:"Repository",documentType:"Official archive index",publisher:"National Archives of India",url:"https://www.abhilekh-patal.in/jspui/",whatItProves:"That archival descriptions and digitised records can be searched through the official repository.",whatItDoesNotProve:"That an absent search result means the historical event did not occur."}
];
