export type FreedomRecord={id:string;name:string;state:string;district:string;period:string;movement:string;record:string;sourceUrl:string;sourceTitle:string;reviewNote:string;regions?:string[]};

export type CellularJailProvinceRecord={province:string;count:number;note?:string};

export const cellularJailSource={
  title:"Ministry of Culture — Rajya Sabha Unstarred Question No. 985",
  date:"13 February 2025",
  period:"1909–1938",
  url:"https://sansad.in/getFile/annex/267/AU985_1iedDF.pdf?source=pqars",
  definition:"Revolutionaries recorded by the Directorate of Art and Culture, Andaman & Nicobar Administration as jailed in Cellular Jail from 1909 to 1938, grouped by the province/state labels printed in the parliamentary annexure.",
  limitation:"This is a Cellular Jail incarceration count, not a count of every participant in India's freedom struggle. Historical Bengal is undivided Bengal and must not be treated as present-day West Bengal alone."
} as const;

export const cellularJailProvinceRecords:CellularJailProvinceRecord[]=[
  {province:"Bengal",count:398,note:"Undivided Bengal; not present-day West Bengal alone"},
  {province:"Punjab",count:95},
  {province:"Maharashtra",count:3},
  {province:"Bihar",count:17},
  {province:"Uttar Pradesh",count:18},
  {province:"Kerala",count:14},
  {province:"Andhra Pradesh",count:8},
  {province:"Odisha",count:5},
  {province:"Himachal / NW Frontier / Tamil Nadu / state unknown",count:27,note:"Combined category as published; cannot be separated from this source"}
];

export const cellularJailTotal=cellularJailProvinceRecords.reduce((sum,item)=>sum+item.count,0);

export type FreedomRegisterSource={id:string;title:string;publisher:string;reportedCoverage:string;includes:string;doesNotInclude:string;url:string;status:"Aggregate loaded"|"Profiles in review"|"Source mapped"};

export const freedomRegisterSources:FreedomRegisterSource[]=[
  {id:"martyrs-dictionary",title:"Dictionary of Martyrs: India's Freedom Struggle",publisher:"Indian Council of Historical Research and Ministry of Culture",reportedCoverage:"About 13,500 martyrs · 1857–1947 · five regional volumes",includes:"People documented as hanged or killed in the freedom struggle, with archival or contemporary references listed for biographical notes.",doesNotInclude:"People who participated and survived, people outside the dictionary's 1857–1947 definition, or proof that every death was discovered.",url:"https://www.pib.gov.in/amritmahotsav/dictionary_book.aspx?lang=2&reg=48",status:"Source mapped"},
  {id:"digital-district-repository",title:"Digital District Repository",publisher:"Ministry of Culture",reportedCoverage:"Approximately 19,000 verified stories reported in 2025",includes:"District-level stories about people, events, places, built heritage and living traditions connected to the freedom struggle.",doesNotInclude:"A clean person-only list or a guarantee that every district contribution has the same archival depth.",url:"https://cmsadmin.amritmahotsav.nic.in/digital-district-repository.htm",status:"Profiles in review"},
  {id:"central-pension-register",title:"Swatantrata Sainik Samman records",publisher:"Ministry of Home Affairs",reportedCoverage:"Central pension recognition records and a published name list through 30 November 2022",includes:"People accepted under the scheme's legal eligibility and evidence rules, plus separately identified eligible dependants in some releases.",doesNotInclude:"Every participant in the freedom struggle; absence from a pension register is not proof of non-participation.",url:"https://www.mha.gov.in/en/divisionofmha/freedom-fighters-rehabilitation-division",status:"Source mapped"},
  {id:"cellular-jail-register",title:"Cellular Jail province table",publisher:"Ministry of Culture / Andaman & Nicobar Administration",reportedCoverage:"585 revolutionaries jailed in Cellular Jail · 1909–1938",includes:"The complete published province/category aggregate, including 398 people from undivided Bengal.",doesNotInclude:"A complete list of freedom fighters, every Andaman penal-settlement prisoner, or all resistance before and after the stated period.",url:cellularJailSource.url,status:"Aggregate loaded"}
];

export const freedomRecords:FreedomRecord[]=[
  {id:"velu-nachiyar",name:"Velu Nachiyar",state:"Tamil Nadu",district:"Ramanathapuram / Sivaganga",period:"c. 1730-1796",movement:"Early anti-colonial resistance",record:"The Ministry of Culture profile describes her alliance-building and armed campaign against the East India Company before the nineteenth-century mass movements.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?312=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official commemorative narrative; archival corroboration of individual episode details remains required."},
  {id:"kittur-rani-chennamma",name:"Kittur Rani Chennamma",state:"Karnataka",district:"Belagavi",period:"1778-1829",movement:"Kittur resistance",record:"The official profile records her armed opposition to British refusal to recognise Kittur's succession and her subsequent imprisonment at Bailhongal.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?188=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official commemorative profile based on a civil-service academy publication."},
  {id:"tirot-sing",name:"U Tirot Sing Syiem",state:"Meghalaya",district:"West Khasi Hills",period:"early nineteenth century-1835",movement:"Anglo-Khasi War",record:"The Ministry of Culture profile records his leadership against British expansion into the Khasi Hills, guerrilla resistance, capture and deportation to Dhaka.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?57=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official public narrative; event chronology should be paired with colonial and Khasi records."},
  {id:"veer-surendra-sai",name:"Veer Surendra Sai",state:"Odisha",district:"Sambalpur",period:"1809-1884",movement:"Sambalpur resistance and 1857",record:"The official record describes his claim in Sambalpur, imprisonment, release during 1857, guerrilla resistance, rearrest and detention at Asirgarh.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?1978=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Long-form official narrative; judicial and administrative documents remain separate source work."},
  {id:"peer-ali-khan",name:"Peer Ali Khan",state:"Bihar",district:"Patna",period:"c. 1812-1857",movement:"Revolt of 1857",record:"The Ministry of Culture profile records his role as a Patna bookseller involved in organising the July 1857 uprising and his execution by the colonial administration.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?328=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"The official narrative itself notes uncertainty about birthplace; that uncertainty is preserved."},
  {id:"birsa-munda",name:"Birsa Munda",state:"Jharkhand",district:"Khunti",period:"c. 1875-1900",movement:"Munda resistance",record:"The official repository links Birsa's leadership to resistance against British domination, records imprisonment in the 1890s and death in colonial custody in 1900.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?310=",sourceTitle:"Ministry of Culture - Digital District Repository",reviewNote:"Profile cites a Department of Posts publication; a fuller dossier needs land, police and prison records."},
  {id:"alluri-sitarama-raju",name:"Alluri Sitarama Raju",state:"Andhra Pradesh",district:"Visakhapatnam / Agency areas",period:"1897-1924",movement:"Rampa Rebellion",record:"The official repository connects his leadership of the 1922-24 Rampa Rebellion with tribal opposition to colonial forest restrictions.",sourceUrl:"https://amritmahotsav.nic.in/district-reopsitory-detail.htm?16=",sourceTitle:"Ministry of Culture - Digital District Repository",reviewNote:"Official commemorative profile; district boundaries and episode-level claims require archival indexing."},
  {id:"khudiram-bose",name:"Khudiram Bose",state:"West Bengal",district:"Midnapore / Muzaffarpur",period:"1889-1908",movement:"Anushilan Samiti and Muzaffarpur case",record:"The Ministry of Culture profile records his participation with Prafulla Chaki in the 1908 attempt to kill Magistrate Douglas Kingsford, the unintended deaths of two women, his arrest, conviction and execution at age 18.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?303=",sourceTitle:"Ministry of Culture - Khudiram Bose",reviewNote:"Official commemorative narrative; the victims, trial record and disputed episode details must remain part of a full dossier.",regions:["West Bengal","Bengal-linked records"]},
  {id:"benoy-basu",name:"Benoy Krishna Basu",state:"Undivided Bengal",district:"Munshiganj / Dhaka / Kolkata",period:"1908-1930",movement:"Bengal Volunteers and Writers' Building attack",record:"The official profile records Benoy's Bengal Volunteers activity, the 1930 attack on colonial police official N. S. Simpson at Writers' Building and his death after refusing capture.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?11063=",sourceTitle:"Ministry of Culture - Benoy Badal Dinesh",reviewNote:"Combined official narrative. Munshiganj and Dhaka are in present-day Bangladesh; this card is not assigned solely to modern West Bengal.",regions:["Undivided Bengal","Bengal-linked records"]},
  {id:"badal-gupta",name:"Badal Gupta",state:"Undivided Bengal",district:"Bikrampur, Dhaka / Kolkata",period:"1912-1930",movement:"Bengal Volunteers and Writers' Building attack",record:"The official profile records Badal's Bengal Volunteers membership, participation in the 8 December 1930 Writers' Building attack and death after consuming cyanide rather than surrendering.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?11063=",sourceTitle:"Ministry of Culture - Benoy Badal Dinesh",reviewNote:"Combined official narrative. His birthplace lies in present-day Bangladesh; the Kolkata event does not make the whole biography a present-day West Bengal record.",regions:["Undivided Bengal","Bengal-linked records"]},
  {id:"dinesh-gupta",name:"Dinesh Chandra Gupta",state:"Undivided Bengal",district:"Munshiganj / Kolkata",period:"1911-1931",movement:"Bengal Volunteers and Writers' Building attack",record:"The official profile records Dinesh's Bengal Volunteers activity, participation in the Writers' Building attack, survival of the immediate confrontation and execution at Alipore Jail on 7 July 1931.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?11063=",sourceTitle:"Ministry of Culture - Benoy Badal Dinesh",reviewNote:"Combined official narrative; individual trial and prison documents still require their own record-level review.",regions:["Undivided Bengal","Bengal-linked records"]},
  {id:"pritilata-waddedar",name:"Pritilata Waddedar",state:"Undivided Bengal",district:"Chittagong / Kolkata",period:"1911-1932",movement:"Chittagong revolutionary movement",record:"The Ministry of Culture profile records her work with Surya Sen's group, leadership in the 1932 Pahartali European Club attack and death after consuming cyanide while injured and facing capture.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?137=",sourceTitle:"Ministry of Culture - Pritilata Waddedar",reviewNote:"Chittagong is in present-day Bangladesh. The official commemorative profile is a starting source, not a substitute for police, trial and movement records.",regions:["Undivided Bengal","Bengal-linked records"]},
  {id:"kalpana-dutta",name:"Kalpana Dutta",state:"Undivided Bengal",district:"Chittagong / Kolkata",period:"1913-1995",movement:"Chittagong revolutionary movement",record:"The official profile records her membership in Surya Sen's group, involvement in the Chittagong armoury movement, arrest, life sentence and release after six years.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?136=",sourceTitle:"Ministry of Culture - Kalpana Dutta",reviewNote:"The source mixes Chittagong and Kolkata context; this is indexed under undivided Bengal rather than assigned exclusively to a current state.",regions:["Undivided Bengal","Bengal-linked records"]},
  {id:"surya-sen",name:"Surya Sen",state:"Undivided Bengal",district:"Chittagong",period:"1894-1934",movement:"Chittagong Armoury Raid",record:"The Ministry of Culture repository records his leadership of the 18 April 1930 Chittagong armoury raid and provisional revolutionary government, later capture and execution in January 1934.",sourceUrl:"https://amritmahotsav.nic.in/district-reopsitory-detail.htm?2556=",sourceTitle:"Ministry of Culture - Chittagong Armoury Raid",reviewNote:"The event page identifies a 65-person operation and multiple named participants; each individual still needs a separate source chain.",regions:["Undivided Bengal","Bengal-linked records"]},
  {id:"bina-das",name:"Bina Das",state:"West Bengal",district:"Nadia / Kolkata",period:"1911-1986",movement:"Chhatri Sangha, revolutionary action and Quit India",record:"The official profile records her 1932 attempt to shoot Bengal Governor Stanley Jackson, nine-year sentence, later Quit India imprisonment and service in the Bengal and West Bengal legislatures.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?278=",sourceTitle:"Ministry of Culture - Bina Das",reviewNote:"Official public narrative; her own memoir, court statement and prison records should be linked in a complete dossier.",regions:["West Bengal","Bengal-linked records"]},
  {id:"bagha-jatin",name:"Jatindranath Mukherjee (Bagha Jatin)",state:"Undivided Bengal / Odisha",district:"Kushtia / Kolkata / Balasore",period:"1879-1915",movement:"Jugantar and the Indo-German revolutionary plan",record:"The official repository describes his Jugantar leadership, planning for armed insurrection during the First World War and death after the September 1915 confrontation near Balasore.",sourceUrl:"https://amritmahotsav.nic.in/district-reopsitory-detail.htm?2519=",sourceTitle:"Ministry of Culture - Bagha Jatin",reviewNote:"His birthplace is in present-day Bangladesh and the final confrontation was in Odisha; the cross-border geography is preserved.",regions:["Undivided Bengal","Odisha","Bengal-linked records"]},
  {id:"barindra-kumar-ghosh",name:"Barindra Kumar Ghosh",state:"West Bengal",district:"Hooghly / Kolkata / Cellular Jail",period:"1880-1959",movement:"Jugantar and Alipore Bomb Case",record:"The official profile records his role in Jugantar, recruitment and arms activity, conviction in the Alipore Bomb Case, commutation to life imprisonment and deportation to Cellular Jail in 1909.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?91=",sourceTitle:"Ministry of Culture - Barindra Kumar Ghosh",reviewNote:"Official commemorative narrative; Alipore trial and Cellular Jail records remain the controlling primary-document work.",regions:["West Bengal","Bengal-linked records"]},
  {id:"matangini-hazra",name:"Matangini Hazra",state:"West Bengal",district:"Paschim Medinipur",period:"1870-1942",movement:"Civil Disobedience and Quit India",record:"The official profile records her participation in Salt Act protests and the 1942 Tamluk procession in which British Indian police shot her.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?317=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Official narrative; local parallel-government and police records require their own linked dossier.",regions:["West Bengal","Bengal-linked records"]},
  {id:"rani-gaidinliu",name:"Rani Gaidinliu",state:"Manipur",district:"Tamenglong",period:"1915-1993",movement:"Heraka and Naga anti-colonial resistance",record:"The official profile records her joining the Heraka movement, arrest in 1932, life sentence and imprisonment across the Northeast until 1947.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?56=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"The movement's religious, political and later regional contexts need multiple community and archival sources."},
  {id:"kanaklata-barua",name:"Kanaklata Barua",state:"Assam",district:"Sonitpur",period:"1924-1942",movement:"Quit India",record:"The official profile records her participation in the 20 September 1942 procession to Gohpur police station and her death in police firing.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?347=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"Profile cites a Department of Posts special cover; police and procession records remain to be indexed."},
  {id:"komaram-bheem",name:"Komaram Bheem",state:"Telangana",district:"Komaram Bheem Asifabad",period:"c. 1901-1940",movement:"Adivasi land and forest resistance",record:"The official profile records his mobilisation around Jal, Jangal, Jameen and armed resistance to the Hyderabad State administration.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?250=",sourceTitle:"Ministry of Culture - Unsung Heroes",reviewNote:"The cited basis is a Telangana school textbook; administrative, oral-history and community sources are still required."},
  {id:"bhagat-singh",name:"Bhagat Singh",state:"Undivided Punjab",district:"Lyallpur / Lahore",period:"1907-1931",movement:"Hindustan Socialist Republican Association",record:"The official commemorative record identifies Bhagat Singh's revolutionary activity, Lahore Conspiracy Case and execution with Rajguru and Sukhdev on 23 March 1931.",sourceUrl:"https://newindiasamachar.pib.gov.in/WriteReadData/Magazine/2025/Mar/M202503161.pdf",sourceTitle:"Press Information Bureau - New India Samachar",reviewNote:"The government publication is a starting record. Court papers, prison writings and contemporary newspapers require separate links.",regions:["Undivided Punjab","Punjab-linked records"]},
  {id:"sukhdev-thapar",name:"Sukhdev Thapar",state:"Undivided Punjab",district:"Ludhiana / Lahore",period:"1907-1931",movement:"Hindustan Socialist Republican Association",record:"The official commemorative record identifies Sukhdev Thapar as a revolutionary convicted in the Lahore Conspiracy Case and executed with Bhagat Singh and Rajguru on 23 March 1931.",sourceUrl:"https://newindiasamachar.pib.gov.in/WriteReadData/Magazine/2025/Mar/M202503161.pdf",sourceTitle:"Press Information Bureau - New India Samachar",reviewNote:"A shared commemorative source is not a full individual dossier; trial and family records remain to be indexed.",regions:["Undivided Punjab","Punjab-linked records"]},
  {id:"shivaram-rajguru",name:"Shivaram Hari Rajguru",state:"Maharashtra / Undivided Punjab",district:"Pune / Lahore",period:"1908-1931",movement:"Hindustan Socialist Republican Association",record:"The official commemorative record identifies Rajguru's revolutionary activity, conviction in the Lahore Conspiracy Case and execution with Bhagat Singh and Sukhdev on 23 March 1931.",sourceUrl:"https://newindiasamachar.pib.gov.in/WriteReadData/Magazine/2025/Mar/M202503161.pdf",sourceTitle:"Press Information Bureau - New India Samachar",reviewNote:"This cross-regional profile retains both Maharashtra and Lahore context; court and prison sources need a separate chain.",regions:["Maharashtra","Undivided Punjab","Punjab-linked records"]},
  {id:"ram-prasad-bismil",name:"Ram Prasad Bismil",state:"Uttar Pradesh",district:"Shahjahanpur / Kakori / Gorakhpur",period:"1897-1927",movement:"Hindustan Republican Association and Kakori action",record:"The Ministry of Culture profile records his role in revolutionary organisation and the Kakori action, followed by conviction and execution at Gorakhpur Jail in December 1927.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?45=",sourceTitle:"Ministry of Culture - Ram Prasad Bismil",reviewNote:"Official commemorative biography; Kakori trial records and Bismil's writings remain separate primary-source work."},
  {id:"udham-singh",name:"Udham Singh",state:"Punjab",district:"Sangrur / Amritsar / London",period:"1899-1940",movement:"Revolutionary movement and Jallianwala Bagh memory",record:"The official repository connects Udham Singh's later revolutionary action in London to the political memory of the 1919 Jallianwala Bagh massacre and records his execution in 1940.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/district-reopsitory-detail.htm?25230=",sourceTitle:"Ministry of Culture - Udham Singh",reviewNote:"The causal and biographical narrative must be read alongside the London trial file and contemporary records.",regions:["Punjab","Punjab-linked records"]},
  {id:"durgawati-devi",name:"Durgawati Devi (Durga Bhabhi)",state:"Uttar Pradesh / Undivided Punjab",district:"Allahabad / Lahore",period:"1907-1999",movement:"Hindustan Socialist Republican Association",record:"The Ministry of Culture profile records her support for HSRA members, assistance to Bhagat Singh after the Saunders case, and later revolutionary activity.",sourceUrl:"https://cmsadmin.amritmahotsav.nic.in/unsung-heroes-detail.htm?96=",sourceTitle:"Ministry of Culture - Durgawati Devi",reviewNote:"The official profile is a biographical starting point; individual episodes and later life need documentary corroboration.",regions:["Uttar Pradesh","Undivided Punjab","Punjab-linked records"]},
  {id:"jatindra-nath-das",name:"Jatindra Nath Das",state:"West Bengal / Undivided Punjab",district:"Kolkata / Lahore",period:"1904-1929",movement:"Revolutionary movement and Lahore Jail hunger strike",record:"The official profile records his revolutionary activity, imprisonment in the Lahore Conspiracy Case and death after a prolonged hunger strike protesting jail conditions.",sourceUrl:"https://amritmahotsav.nic.in/unsung-heroes-detail.htm?99=",sourceTitle:"Ministry of Culture - Jatindra Nath Das",reviewNote:"His jail protest and death require prison, medical and inquest records in a full dossier.",regions:["West Bengal","Bengal-linked records","Undivided Punjab","Punjab-linked records"]},
  {id:"subhas-chandra-bose",name:"Subhas Chandra Bose",state:"West Bengal",district:"Kolkata / international theatres",period:"1897-1945",movement:"Forward Bloc, Azad Hind Government and INA",record:"The National Archives provides a dedicated doorway to declassified Netaji papers, including files transferred from multiple Union government collections and INA/inquiry records.",sourceUrl:"https://www.nationalarchives.nic.in/en/online-records-national-archives-india/netaji-papers",sourceTitle:"National Archives of India - Netaji Papers",reviewNote:"This points to the primary file corpus; it does not resolve disputed death or alliance interpretations.",regions:["West Bengal","Bengal-linked records"]}
];

export type DocumentRecord={id:string;title:string;person:string;date:string;documentType:string;publisher:string;url:string;whatItProves:string;whatItDoesNotProve:string};
export const documentRecords:DocumentRecord[]=[
  {id:"netaji-papers",title:"Netaji Papers",person:"Subhas Chandra Bose",date:"Declassified collections",documentType:"Official archive collection",publisher:"National Archives of India",url:"https://www.nationalarchives.nic.in/en/online-records-national-archives-india/netaji-papers",whatItProves:"That a defined government-held corpus has been declassified and made available through the archive doorway.",whatItDoesNotProve:"That every public claim about Bose, the INA or his death is established."},
  {id:"netaji-declassification",title:"Government reply on Netaji declassification",person:"Subhas Chandra Bose",date:"Government summary",documentType:"Parliamentary/PIB record",publisher:"Press Information Bureau",url:"https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1594556",whatItProves:"The reported number and originating departments of files transferred and uploaded.",whatItDoesNotProve:"The truth of every proposition contained inside those files."},
  {id:"savarkar-1913",title:"Reference to Savarkar's petition dated 14 November 1913",person:"V. D. Savarkar",date:"14 November 1913",documentType:"Parliamentary record",publisher:"Parliament of India",url:"https://sansad.in/getFile/loksabhaquestions/annex/173/AU4718.pdf?source=pqals",whatItProves:"That the official parliamentary record identifies a petition from the named convict and date.",whatItDoesNotProve:"A partisan verdict about motive, courage, strategy or betrayal."},
  {id:"mookerjee-letter-1950",title:"Nehru's letter to Syama Prasad Mookerjee",person:"Syama Prasad Mookerjee",date:"15 April 1950",documentType:"Published correspondence",publisher:"Nehru Archive / Selected Works",url:"https://nehruarchive.in/documents/to-syama-prasad-mookerjee-15-april-1950-v9jqq1",whatItProves:"The content and date of Nehru's stated position concerning Mookerjee's resignation.",whatItDoesNotProve:"That one correspondent's framing resolves every political dispute."},
  {id:"abhilekh-patal",title:"Abhilekh Patal archival search doorway",person:"Multiple",date:"Repository",documentType:"Official archive index",publisher:"National Archives of India",url:"https://www.abhilekh-patal.in/jspui/",whatItProves:"That archival descriptions and digitised records can be searched through the official repository.",whatItDoesNotProve:"That an absent search result means the historical event did not occur."}
];
