/* eslint-disable @next/next/no-html-link-for-pages */
import type { Metadata } from "next";
import { catalogCoverage, evidenceCatalog } from "../../lib/catalog";
import { getSystemStatus } from "../../lib/system-status";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Data operations — India Evidence Dashboard",description:"Public operational status, evidence coverage and release gates for the India Evidence Dashboard."};

export default async function OperationsPage(){
  const status=await getSystemStatus();
  const sourceTotal=status.availableSources+status.restrictedSources+status.unavailableSources+status.checkFailedSources;
  return <main className="operations-shell"><header className="record-header"><a className="record-brand" href="/"><span className="brand-mark"/><b>India Evidence <em>Dashboard</em></b></a><nav><a href="/catalog">Catalogue</a><a href="/explore">States &amp; UTs</a><a href="/editorial">Editorial ledger</a><a href="/corrections">Corrections</a></nav><a className="record-compare" href="/">National view</a></header>
    <section className="operations-hero"><p className="eyebrow">Public operations register</p><h1>What is running.<br/><span>What is still gated.</span></h1><p>This page exposes useful coverage and freshness facts without revealing credentials, provider configuration, user identities or database internals.</p></section>
    <section className="operations-body"><div className="operations-metrics"><article><span>Jurisdiction records</span><strong>{status.jurisdictions || 37}</strong><p>India plus all 36 current states and union territories.</p></article><article><span>Defined evidence domains</span><strong>{evidenceCatalog.length}</strong><p>{catalogCoverage.loaded + catalogCoverage.connected} loaded or connected; all other gaps remain visible.</p></article><article><span>Stored source records</span><strong>{status.sources}</strong><p>{sourceTotal ? `${status.availableSources} currently reachable after the latest scheduled check.` : "Status store is temporarily unavailable."}</p></article><article><span>Stored evidence records</span><strong>{status.evidenceRecords}</strong><p>{status.correctionRequests} privacy-minimised correction requests are also in the review store.</p></article></div>
      <div className="operations-ledger"><div><p className="eyebrow">Pipeline register</p><h2>Data does not become evidence automatically.</h2></div><ol><li data-state="running"><b>Running</b><strong>Public weather-model connector</strong><span>Current reference-grid conditions with retrieval time and model limitation.</span></li><li data-state="running"><b>Running</b><strong>CPCB station connector</strong><span>Official station records through data.gov.in; never represented as a statewide average.</span></li><li data-state="running"><b>Running</b><strong>Source-health scheduler</strong><span>Daily public-link checks record reachability without changing verdicts automatically.</span></li><li data-state="periodic"><b>Periodic</b><strong>Government publications</strong><span>Budgets, audits, crime, education, health and forest evidence update only when sources release data.</span></li><li data-state="gated"><b>Release gate</b><strong>Editorial production access</strong><span>Public reading is live. Named editorial onboarding remains held until the production identity configuration and two-user approval test pass.</span></li><li data-state="gated"><b>Release gate</b><strong>Citizen photos and precise location</strong><span>No upload or precise-location persistence is enabled before moderation, retention and authority-routing controls are approved.</span></li></ol></div>
      <aside className="operations-freshness"><div><span>Last recorded source check</span><strong>{status.lastSourceCheck ? new Date(status.lastSourceCheck).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"})+" IST" : "No successful timestamp available"}</strong></div><a href="/api/system/status">Open machine-readable public status →</a><a href="/catalog">Inspect the complete coverage catalogue →</a></aside>
    </section><footer className="record-footer"><a href="/">← National dashboard</a><a href="/catalog">Evidence catalogue</a><a href="/editorial">Editorial ledger</a><a href="/corrections">Request a correction</a></footer></main>;
}
